### ISSUE TITLE
start.sh

### ISSUE THREAD

**Issue by fretn** [alexandrovteam/curatr#15]
step 3. of the Vagrant howto says that start.sh needs to  be edited, but there is no start.sh, the sh files that are found contain less than 31 lines too, can you please update the howto ?

**Comment by andy-d-palmer** [comment]
Ah. At some point I split the start.sh into two scripts (base.sh and start.sh) and forgot to update the line numbering. Fixed now.

**Comment by fretn** [comment]
great, thanks
